export interface ComponentCategory {
  id: string
  name: string
  iconName: string
  gradient: string
  patterns: string[]
}

export const CATEGORIES: ComponentCategory[] = [
  {
    id: 'charts',
    name: 'Charts',
    iconName: 'BarChart3',
    gradient: 'from-blue-500 to-cyan-500',
    patterns: ['area-chart', 'bar-chart', 'line-chart', 'pie-chart', 'radar-chart'],
  },
  {
    id: 'ui',
    name: 'UI Components',
    iconName: 'Calendar',
    gradient: 'from-violet-500 to-purple-500',
    patterns: [
      'calendar',
      'combobox',
      'table',
      'tabs',
      'choicebox',
      'color-picker',
      'dropzone',
      'gantt',
      'kanban',
      'kbd',
      'list',
      'mini-calendar',
      'qr-code',
      'rating',
      'snippet',
      'status',
      'tags',
      'terminal',
      'video-player',
      'credit-card',
      'image-crop',
      'image-zoom',
      'code-block',
      'code-editor',
      'code-tabs',
      'minimal-tiptap',
      'relative-time',
      'sliding-number',
      'counting-number',
      'counter',
      'ticker',
    ],
  },
  {
    id: 'animations',
    name: 'Animations',
    iconName: 'Sparkles',
    gradient: 'from-amber-500 to-orange-500',
    patterns: [
      'animated-',
      '3d-',
      'motion-',
      'ripple',
      'vortex',
      'particles',
      'meteors',
      'shooting-stars',
      'fireworks',
      'sparkles',
      'smoke',
      'carousel',
      'marquee',
      'shuffle',
      'kaleidoscope',
      'spiral-animation',
      'curved-loop',
    ],
  },
  {
    id: 'backgrounds',
    name: 'Background Effects',
    iconName: 'Layers',
    gradient: 'from-emerald-500 to-teal-500',
    patterns: [
      'aurora-background',
      'background-',
      'flickering-grid',
      'retro-grid',
      'dot-pattern',
      'grid-pattern',
      'interactive-grid-pattern',
      'hexagon-background',
      'bubble-background',
      'light-waves-background',
      'warp-background',
      'wavy-background',
      'shape-landing-hero',
    ],
  },
  {
    id: 'text',
    name: 'Text Effects',
    iconName: 'Type',
    gradient: 'from-pink-500 to-rose-500',
    patterns: [
      'blur-text',
      'colourful-text',
      'decrypted-text',
      'falling-text',
      'flip-words',
      'fuzzy-text',
      'glitch-text',
      'gradient-text',
      'highlight-text',
      'line-shadow-text',
      'rolling-text',
      'rotating-text',
      'scrambled-text',
      'shimmering-text',
      'splitting-text',
      'text-cursor',
      'text-generate-effect',
      'text-hover-effect',
      'text-pressure',
      'text-reveal',
      'text-trail',
      'true-focus',
      'typing-text',
      'writing-text',
      'variable-proximity',
      'circular-text',
      'apple-hello-effect',
    ],
  },
  {
    id: 'navigation',
    name: 'Navigation',
    iconName: 'Navigation',
    gradient: 'from-indigo-500 to-blue-500',
    patterns: [
      'navbar-',
      'dock',
      'mac-os-dock',
      'menu-dock',
      'message-dock',
      'limelight-nav',
    ],
  },
  {
    id: 'hooks',
    name: 'Hooks',
    iconName: 'Code2',
    gradient: 'from-slate-500 to-gray-600',
    patterns: ['use-'],
  },
  {
    id: 'shaders',
    name: 'Shaders',
    iconName: 'Palette',
    gradient: 'from-fuchsia-500 to-pink-500',
    patterns: ['-shaders'],
  },
  {
    id: 'utility',
    name: 'Utility',
    iconName: 'Package',
    gradient: 'from-gray-500 to-slate-500',
    patterns: [], // Catch-all for uncategorized
  },
]

// All 257 shadcn components
export const SHADCN_COMPONENTS = [
  '2d-noise-contours-shaders',
  '3d-card',
  '3d-marquee',
  '3d-pin',
  'abstract-mod-shaders',
  'accretion-shaders',
  'advanced-tunnel-shaders',
  'ai',
  'android',
  'animated-beam',
  'animated-cursor',
  'animated-modal',
  'animated-testimonials',
  'animated-tooltip',
  'announcement',
  'apple-cards-carousel',
  'apple-hello-effect',
  'area-chart-01',
  'area-chart-02',
  'area-chart-03',
  'area-chart-04',
  'area-chart-05',
  'area-chart-06',
  'area-chart-07',
  'area-chart-08',
  'area-chart-09',
  'area-chart-10',
  'aurora-background',
  'aurora-shaders',
  'avatar-group',
  'background-beams',
  'background-beams-with-collision',
  'background-boxes',
  'background-circles',
  'background-gradient',
  'background-gradient-animation',
  'background-paths',
  'banner',
  'bar-chart-01',
  'bar-chart-02',
  'bar-chart-03',
  'bar-chart-04',
  'bar-chart-05',
  'bar-chart-06',
  'bar-chart-07',
  'bar-chart-08',
  'bar-chart-09',
  'bar-chart-10',
  'binary-shaders',
  'biomine-shaders',
  'blocks',
  'blur-text',
  'bubble-background',
  'calendar',
  'cellular-tiled-tunnel-shaders',
  'choicebox',
  'circular-text',
  'code-block',
  'code-editor',
  'code-tabs',
  'color-picker',
  'colourful-text',
  'combobox',
  'comparison',
  'container-text-flip',
  'copy-button',
  'corner-accent-button',
  'cosmic-discs-shaders',
  'cosmic-waves-shaders',
  'counter',
  'counting-number',
  'credit-card',
  'cursor',
  'curved-loop',
  'decrypted-text',
  'desert-sand-shaders',
  'dialog-stack',
  'digital-tunnel-shaders',
  'dock',
  'dot-pattern',
  'dropzone',
  'etheral-shadow',
  'extruded-mobius-spiral-shaders',
  'falling-text',
  'fire-3d-shaders',
  'fireworks-background',
  'flickering-grid',
  'flip-button',
  'flip-words',
  'fractals-shaders',
  'fuzzy-text',
  'gantt',
  'github-stars-button',
  'glimpse',
  'glitch-shaders',
  'glitch-text',
  'gradient-mesh-shaders',
  'gradient-text',
  'grid-pattern',
  'hexagon-background',
  'hexagon-grid-pattern-shaders',
  'highlight-text',
  'hologram-shaders',
  'icon-button',
  'image-crop',
  'image-zoom',
  'input-button',
  'interactive-grid-pattern',
  'iphone-15-pro',
  'kaleidoscope',
  'kanban',
  'kbd',
  'light-waves-background',
  'limelight-nav',
  'line-chart-01',
  'line-chart-02',
  'line-chart-03',
  'line-chart-04',
  'line-chart-05',
  'line-chart-06',
  'line-chart-07',
  'line-chart-08',
  'line-chart-09',
  'line-chart-10',
  'line-shadow-text',
  'liquid-button',
  'list',
  'mac-os-dock',
  'magnetic',
  'magnetic-button',
  'mandelbrot-pattern-decoration-shaders',
  'marquee',
  'matrix-shaders',
  'menu-dock',
  'message-dock',
  'meteors',
  'mini-calendar',
  'minimal-jigsaw-shaders',
  'minimal-tiptap',
  'mobius-sierpinski-shaders',
  'monster-tunnel-shaders',
  'motion-effect',
  'motion-highlight',
  'navbar-01',
  'navbar-02',
  'navbar-03',
  'navbar-04',
  'navbar-05',
  'navbar-06',
  'navbar-07',
  'navbar-08',
  'navbar-09',
  'navbar-10',
  'navbar-11',
  'navbar-12',
  'navbar-13',
  'navbar-14',
  'navbar-15',
  'navbar-16',
  'navbar-17',
  'navbar-18',
  'nebula-shaders',
  'noise-shaders',
  'oldschool-tube-shaders',
  'particles',
  'patterns',
  'perspex-web-lattice-shaders',
  'pie-chart-01',
  'pie-chart-02',
  'pie-chart-03',
  'pie-chart-04',
  'pie-chart-05',
  'pie-chart-06',
  'pie-chart-07',
  'pie-chart-08',
  'pie-chart-09',
  'pie-chart-10',
  'pie-chart-11',
  'pill',
  'pin-list',
  'pixel-image',
  'plasma-shaders',
  'poincare-disc-animation-shaders',
  'psychedelic-spiral',
  'pyramid-pattern-shaders',
  'qr-code',
  'radar-chart-01',
  'radar-chart-02',
  'radar-chart-03',
  'radar-chart-04',
  'radar-chart-05',
  'radar-chart-06',
  'radar-chart-07',
  'radar-chart-08',
  'radar-chart-09',
  'radar-chart-10',
  'radar-chart-11',
  'radar-chart-12',
  'random-grid-subdivision-shaders',
  'rating',
  'raymarching-shaders',
  'relative-time',
  'retro-grid',
  'ripple',
  'ripple-button',
  'ripple-shaders',
  'ripples-in-black-shaders',
  'rolling-text',
  'rotating-text',
  'safari',
  'sandbox',
  'scrambled-text',
  'scroll-velocity',
  'sea-shaders',
  'shape-landing-hero',
  'shimmering-text',
  'shooting-stars',
  'shuffle',
  'sigmoids-sines-shaders',
  'simplex-truchet-weave-shaders',
  'singularity-shaders',
  'sliding-number',
  'smoke',
  'smoke-shaders',
  'smooth-noise-contours-shaders',
  'smooth-voronoi-contours-shaders',
  'snippet',
  'soap-bubbles-2d-shaders',
  'sparkles',
  'sparks-drifting-shaders',
  'sphere-field-shaders',
  'spinner',
  'spiral-animation',
  'splitting-text',
  'starry-planes-shaders',
  'stars-scrolling-wheel',
  'status',
  'synthwave-canyon-shaders',
  'table',
  'tabs',
  'tags',
  'terminal',
  'text-cursor',
  'text-generate-effect',
  'text-hover-effect',
  'text-pressure',
  'text-reveal',
  'text-reveal-button',
  'text-trail',
  'theme-switcher',
  'theme-toggle-button',
  'three-tap-voronoi-shaders',
  'ticker',
  'triangle-mesh-incircles-shaders',
  'truchet-kaleidoscope-shaders',
  'truchet-shaders',
  'true-focus',
  'tunnel-shaders',
  'typing-text',
  'use-boolean',
  'use-click-anywhere',
  'use-copy-to-clipboard',
  'use-countdown',
  'use-counter',
  'use-dark-mode',
  'use-debounce-callback',
  'use-debounce-value',
  'use-document-title',
  'use-event-callback',
  'use-event-listener',
  'use-hover',
  'use-intersection-observer',
  'use-interval',
  'use-is-client',
  'use-is-mounted',
  'use-isomorphic-layout-effect',
  'use-local-storage',
  'use-map',
  'use-media-query',
  'use-mouse-position',
  'use-on-click-outside',
  'use-read-local-storage',
  'use-resize-observer',
  'use-screen',
  'use-script',
  'use-scroll-lock',
  'use-session-storage',
  'use-step',
  'use-ternary-dark-mode',
  'use-timeout',
  'use-toggle',
  'use-unmount',
  'use-window-size',
  'variable-proximity',
  'video-player',
  'vortex',
  'warp-background',
  'warped-noise-shaders',
  'water-shaders',
  'waves-shaders',
  'wavy-background',
  'worley-noise-shaders',
  'writing-text',
] as const

export type ShadcnComponentName = (typeof SHADCN_COMPONENTS)[number]

export interface CategorizedComponent {
  name: string
  displayName: string
  category: ComponentCategory
}

/**
 * Categorize a component based on its name
 */
export function categorizeComponent(name: string): ComponentCategory {
  for (const category of CATEGORIES) {
    if (category.id === 'utility') continue // Skip utility (catch-all)

    for (const pattern of category.patterns) {
      if (name.includes(pattern)) {
        return category
      }
    }
  }

  // Return utility as catch-all
  return CATEGORIES.find((c) => c.id === 'utility')!
}

/**
 * Convert component name to display name
 * e.g., "area-chart-01" -> "Area Chart 01"
 */
export function toDisplayName(name: string): string {
  return name
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

/**
 * Get all categorized components
 */
export function getCategorizedComponents(): CategorizedComponent[] {
  return SHADCN_COMPONENTS.map((name) => ({
    name,
    displayName: toDisplayName(name),
    category: categorizeComponent(name),
  }))
}

/**
 * Get components grouped by category
 */
export function getComponentsByCategory(): Map<string, CategorizedComponent[]> {
  const grouped = new Map<string, CategorizedComponent[]>()

  for (const category of CATEGORIES) {
    grouped.set(category.id, [])
  }

  for (const name of SHADCN_COMPONENTS) {
    const category = categorizeComponent(name)
    const components = grouped.get(category.id) || []
    components.push({
      name,
      displayName: toDisplayName(name),
      category,
    })
    grouped.set(category.id, components)
  }

  return grouped
}
