#!/usr/bin/env tsx
/**
 * Institution Development Environment Switcher
 *
 * This script allows developers to easily switch between different institution
 * Supabase projects for local development.
 *
 * Usage:
 *   npx tsx scripts/switch-institution.ts main
 *   npx tsx scripts/switch-institution.ts dental
 *   npm run dev:main     (shorthand)
 *   npm run dev:dental   (shorthand)
 */

import * as fs from 'fs'
import * as path from 'path'

// Available institutions configuration
interface InstitutionEnv {
  id: string
  name: string
  supabaseUrl: string
  supabaseAnonKey: string
  siteUrl: string
  features: string
}

const INSTITUTIONS: Record<string, InstitutionEnv> = {
  main: {
    id: 'main',
    name: 'JKKN Institutions',
    supabaseUrl: 'https://pmqodbfhsejbvfbmsfeq.supabase.co',
    supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcW9kYmZoc2VqYnZmYm1zZmVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NTAzMDcsImV4cCI6MjA3OTMyNjMwN30.v2DXQ-0Aa1UTotrzWguqWRYR7Eh8mkXcwCYxBjgiFmI',
    siteUrl: 'http://localhost:3000',
    features: 'blog,careers,page-builder,analytics,events,gallery,testimonials,newsletter',
  },
  dental: {
    id: 'dental',
    name: 'JKKN Dental College and Hospital',
    supabaseUrl: 'https://wnmyvbnqldukeknnmnpl.supabase.co',
    supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubXl2Ym5xbGR1a2Vrbm5tbnBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNDQxNTMsImV4cCI6MjA4MjkyMDE1M30.A5YnEqrUdtu7fOpxgHGzMghr1grIxhDqCF4Q_2BwZhQ',
    siteUrl: 'http://localhost:3000',
    features: 'blog,careers,page-builder,analytics,faculty-directory,course-catalog,admissions,testimonials',
  },
  // Add more institutions as needed:
  // 'arts-science': { ... },
  // 'engineering': { ... },
  // 'pharmacy': { ... },
  // 'nursing': { ... },
}

function generateEnvContent(inst: InstitutionEnv, serviceRoleKey?: string): string {
  return `# Auto-generated by switch-institution.ts
# Institution: ${inst.name}
# Generated: ${new Date().toISOString()}

# =============================================================================
# INSTITUTION IDENTITY
# =============================================================================
NEXT_PUBLIC_INSTITUTION_ID=${inst.id}
NEXT_PUBLIC_INSTITUTION_NAME="${inst.name}"
NEXT_PUBLIC_SITE_URL=${inst.siteUrl}

# =============================================================================
# SUPABASE CONFIGURATION
# =============================================================================
NEXT_PUBLIC_SUPABASE_URL=${inst.supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${inst.supabaseAnonKey}

# Service role key (get from Supabase Dashboard → Settings → API)
# IMPORTANT: Keep this secret! Never commit to git.
SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey || 'YOUR_SERVICE_ROLE_KEY_HERE'}

# =============================================================================
# FEATURE FLAGS
# =============================================================================
NEXT_PUBLIC_FEATURES=${inst.features}

# =============================================================================
# DEBUG (Development only)
# =============================================================================
NEXT_PUBLIC_DEBUG=true
`
}

function switchInstitution(institutionId: string): void {
  const projectRoot = path.resolve(__dirname, '..')
  const envLocalPath = path.join(projectRoot, '.env.local')
  const serviceKeyPath = path.join(projectRoot, `.env.${institutionId}.servicekey`)

  // Validate institution
  const inst = INSTITUTIONS[institutionId]
  if (!inst) {
    console.error(`\n❌ Unknown institution: "${institutionId}"`)
    console.log('\nAvailable institutions:')
    Object.keys(INSTITUTIONS).forEach(id => {
      console.log(`  - ${id}: ${INSTITUTIONS[id].name}`)
    })
    process.exit(1)
  }

  // Check for service role key file
  let serviceRoleKey: string | undefined
  if (fs.existsSync(serviceKeyPath)) {
    serviceRoleKey = fs.readFileSync(serviceKeyPath, 'utf-8').trim()
    console.log(`✅ Found service role key in .env.${institutionId}.servicekey`)
  } else {
    console.log(`\n⚠️  No service role key file found at .env.${institutionId}.servicekey`)
    console.log(`   Create this file with your service role key for full admin access.`)
    console.log(`   Get it from: ${inst.supabaseUrl.replace('.supabase.co', '')}/project/settings/api`)
  }

  // Generate and write .env.local
  const envContent = generateEnvContent(inst, serviceRoleKey)
  fs.writeFileSync(envLocalPath, envContent)

  console.log(`\n✅ Switched to: ${inst.name}`)
  console.log(`   Supabase: ${inst.supabaseUrl}`)
  console.log(`   Features: ${inst.features}`)
  console.log(`\n📝 Environment written to: .env.local`)
  console.log(`\n🚀 Run 'npm run dev' to start development server`)
}

function listInstitutions(): void {
  console.log('\n📋 Available Institutions:\n')
  Object.entries(INSTITUTIONS).forEach(([id, inst]) => {
    console.log(`  ${id}`)
    console.log(`    Name: ${inst.name}`)
    console.log(`    Supabase: ${inst.supabaseUrl}`)
    console.log(`    Features: ${inst.features}`)
    console.log('')
  })
  console.log('Usage: npx tsx scripts/switch-institution.ts <institution-id>')
  console.log('   or: npm run dev:<institution-id>')
}

// Main execution
const args = process.argv.slice(2)
const command = args[0]

if (!command || command === '--help' || command === '-h') {
  listInstitutions()
} else if (command === '--list' || command === '-l') {
  listInstitutions()
} else {
  switchInstitution(command)
}
