#!/usr/bin/env tsx
/**
 * Institution Development Environment Switcher
 *
 * This script allows developers to easily switch between different institution
 * Supabase projects for local development.
 *
 * Usage:
 *   npx tsx scripts/switch-institution.ts main
 *   npx tsx scripts/switch-institution.ts dental
 *   npm run dev:main     (shorthand)
 *   npm run dev:dental   (shorthand)
 *
 * Optional sidecar files (all git-ignored under .env*):
 *   .env.{institutionId}.servicekey  — Supabase service role key (one value
 *                                       per file, raw token). Enables full
 *                                       admin operations in local dev.
 *   .env.{institutionId}.jkkn-api    — MyJKKN Staff API sync config (KEY=VALUE
 *                                       lines). Used by engineering's faculty
 *                                       sync pipeline. Expected keys:
 *                                         JKKN_API_BASE_URL
 *                                         JKKN_API_KEY
 *                                         JKKN_ENGINEERING_INSTITUTION_ID
 */

import * as fs from 'fs'
import * as path from 'path'

// Available institutions configuration
interface InstitutionEnv {
  id: string
  name: string
  supabaseUrl: string
  supabaseAnonKey: string
  siteUrl: string
  features: string
  mediaBucket: string
}

const INSTITUTIONS: Record<string, InstitutionEnv> = {
  main: {
    id: 'main',
    name: 'JKKN Institutions',
    supabaseUrl: 'https://pmqodbfhsejbvfbmsfeq.supabase.co',
    supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcW9kYmZoc2VqYnZmYm1zZmVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NTAzMDcsImV4cCI6MjA3OTMyNjMwN30.v2DXQ-0Aa1UTotrzWguqWRYR7Eh8mkXcwCYxBjgiFmI',
    siteUrl: 'http://localhost:3000',
    features: 'blog,careers,page-builder,analytics,events,gallery,testimonials,newsletter,course-catalog',
    mediaBucket: 'cms-media',
  },
  dental: {
    id: 'dental',
    name: 'JKKN Dental College and Hospital',
    supabaseUrl: 'https://wnmyvbnqldukeknnmnpl.supabase.co',
    supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubXl2Ym5xbGR1a2Vrbm5tbnBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNDQxNTMsImV4cCI6MjA4MjkyMDE1M30.A5YnEqrUdtu7fOpxgHGzMghr1grIxhDqCF4Q_2BwZhQ',
    siteUrl: 'http://localhost:3000',
    features: 'blog,careers,page-builder,analytics,faculty-directory,course-catalog,admissions,testimonials',
    mediaBucket: 'media',
  },
  pharmacy: {
    id: 'pharmacy',
    name: 'JKKN College of Pharmacy',
    supabaseUrl: 'https://rwskookarbolpmtolqkd.supabase.co',
    supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3c2tvb2thcmJvbHBtdG9scWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0MjcwODQsImV4cCI6MjA4MzAwMzA4NH0.Coj77n6921HQcVVyaowug8vmf6Ju2DcM_fCnzaD1Hdc',
    siteUrl: 'http://localhost:3000',
    features: 'blog,careers,page-builder,analytics,comments,newsletter,events,gallery,testimonials,admissions,faculty-directory,course-catalog,research-publications,alumni-network,student-portal,placements',
    mediaBucket: 'media',
  },
  engineering: {
    id: 'engineering',
    name: 'JKKN College of Engineering and Technology',
    supabaseUrl: 'https://kyvfkyjmdbtyimtedkie.supabase.co',
    supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dmZreWptZGJ0eWltdGVka2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NDAxMDQsImV4cCI6MjA4MzAxNjEwNH0.fByamPzYE1G5S1FAXZK1HobVM40zh9Y8N9QlCUNM-6I',
    siteUrl: 'http://localhost:3000',
    features: 'blog,careers,page-builder,analytics,faculty-directory,course-catalog,admissions,research-publications,placements',
    mediaBucket: 'media',
  },
  // Add more institutions as needed:
  // 'arts-science': { ... },
  // 'engineering': { ... },
  // 'nursing': { ... },
}

/**
 * Parse a KEY=VALUE sidecar file (mini env-file format).
 * Splits on the first '=' only so values containing '=' (URLs, JWTs, base64) survive.
 * Returns undefined if the file is missing or has no usable lines, so callers can
 * cleanly skip emitting an empty section into .env.local.
 */
function readEnvSidecar(filePath: string): Record<string, string> | undefined {
  if (!fs.existsSync(filePath)) return undefined
  const vars: Record<string, string> = {}
  for (const rawLine of fs.readFileSync(filePath, 'utf-8').split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq < 0) continue
    const k = line.slice(0, eq).trim()
    const v = line.slice(eq + 1).trim()
    if (k) vars[k] = v
  }
  return Object.keys(vars).length > 0 ? vars : undefined
}

function generateEnvContent(
  inst: InstitutionEnv,
  serviceRoleKey?: string,
  syncVars?: Record<string, string>
): string {
  return `# Auto-generated by switch-institution.ts
# Institution: ${inst.name}
# Generated: ${new Date().toISOString()}

# =============================================================================
# INSTITUTION IDENTITY
# =============================================================================
NEXT_PUBLIC_INSTITUTION_ID=${inst.id}
NEXT_PUBLIC_INSTITUTION_NAME="${inst.name}"
NEXT_PUBLIC_SITE_URL=${inst.siteUrl}

# =============================================================================
# SUPABASE CONFIGURATION
# =============================================================================
NEXT_PUBLIC_SUPABASE_URL=${inst.supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${inst.supabaseAnonKey}

# Service role key (get from Supabase Dashboard → Settings → API)
# IMPORTANT: Keep this secret! Never commit to git.
SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey || 'YOUR_SERVICE_ROLE_KEY_HERE'}

# =============================================================================
# FEATURE FLAGS
# =============================================================================
NEXT_PUBLIC_FEATURES=${inst.features}

# =============================================================================
# STORAGE CONFIGURATION
# =============================================================================
NEXT_PUBLIC_MEDIA_BUCKET=${inst.mediaBucket}

# =============================================================================
# DEBUG (Development only)
# =============================================================================
NEXT_PUBLIC_DEBUG=true
${
  syncVars
    ? `
# =============================================================================
# MyJKKN STAFF API SYNC (sidecar: .env.${inst.id}.jkkn-api)
# =============================================================================
${Object.entries(syncVars).map(([k, v]) => `${k}=${v}`).join('\n')}
`
    : ''
}`
}

function switchInstitution(institutionId: string): void {
  const projectRoot = path.resolve(__dirname, '..')
  const envLocalPath = path.join(projectRoot, '.env.local')
  const serviceKeyPath = path.join(projectRoot, `.env.${institutionId}.servicekey`)
  const syncSidecarPath = path.join(projectRoot, `.env.${institutionId}.jkkn-api`)

  // Validate institution
  const inst = INSTITUTIONS[institutionId]
  if (!inst) {
    console.error(`\n❌ Unknown institution: "${institutionId}"`)
    console.log('\nAvailable institutions:')
    Object.keys(INSTITUTIONS).forEach(id => {
      console.log(`  - ${id}: ${INSTITUTIONS[id].name}`)
    })
    process.exit(1)
  }

  // Check for service role key file
  let serviceRoleKey: string | undefined
  if (fs.existsSync(serviceKeyPath)) {
    serviceRoleKey = fs.readFileSync(serviceKeyPath, 'utf-8').trim()
    console.log(`✅ Found service role key in .env.${institutionId}.servicekey`)
  } else {
    console.log(`\n⚠️  No service role key file found at .env.${institutionId}.servicekey`)
    console.log(`   Create this file with your service role key for full admin access.`)
    console.log(`   Get it from: ${inst.supabaseUrl.replace('.supabase.co', '')}/project/settings/api`)
  }

  // Check for JKKN Staff API sync sidecar (engineering uses this; others may add it later)
  const syncVars = readEnvSidecar(syncSidecarPath)
  if (syncVars) {
    console.log(
      `✅ Found JKKN sync config in .env.${institutionId}.jkkn-api (${Object.keys(syncVars).length} vars)`
    )
  } else if (institutionId === 'engineering') {
    console.log(`\n⚠️  No JKKN sync config at .env.${institutionId}.jkkn-api`)
    console.log(`   Create this file with JKKN_API_BASE_URL, JKKN_API_KEY, and`)
    console.log(`   JKKN_ENGINEERING_INSTITUTION_ID to enable the faculty sync pipeline.`)
  }

  // Generate and write .env.local
  const envContent = generateEnvContent(inst, serviceRoleKey, syncVars)
  fs.writeFileSync(envLocalPath, envContent)

  console.log(`\n✅ Switched to: ${inst.name}`)
  console.log(`   Supabase: ${inst.supabaseUrl}`)
  console.log(`   Features: ${inst.features}`)
  console.log(`\n📝 Environment written to: .env.local`)
  console.log(`\n🚀 Run 'npm run dev' to start development server`)
}

function listInstitutions(): void {
  console.log('\n📋 Available Institutions:\n')
  Object.entries(INSTITUTIONS).forEach(([id, inst]) => {
    console.log(`  ${id}`)
    console.log(`    Name: ${inst.name}`)
    console.log(`    Supabase: ${inst.supabaseUrl}`)
    console.log(`    Features: ${inst.features}`)
    console.log('')
  })
  console.log('Usage: npx tsx scripts/switch-institution.ts <institution-id>')
  console.log('   or: npm run dev:<institution-id>')
}

// Main execution
const args = process.argv.slice(2)
const command = args[0]

if (!command || command === '--help' || command === '-h') {
  listInstitutions()
} else if (command === '--list' || command === '-l') {
  listInstitutions()
} else {
  switchInstitution(command)
}
