import type { GlassPreset } from './styling-types'

// JKKN Brand Glass Presets
export const JKKN_GLASS_PRESETS: GlassPreset[] = [
  {
    id: 'jkkn-green-glass',
    name: 'JKKN Green Glass',
    category: 'brand',
    settings: {
      enabled: true,
      blurLevel: 'lg',
      backgroundOpacity: 10,
      variant: 'light',
      colorTint: 'jkkn-green',
      tintOpacity: 15,
      borderEnabled: true,
      borderOpacity: 20,
      glowEnabled: true,
      glowColor: '#0b6d41',
      glowIntensity: 'subtle',
    },
  },
  {
    id: 'jkkn-gold-glass',
    name: 'JKKN Gold Glass',
    category: 'brand',
    settings: {
      enabled: true,
      blurLevel: 'lg',
      backgroundOpacity: 12,
      variant: 'light',
      colorTint: 'jkkn-gold',
      tintOpacity: 18,
      borderEnabled: true,
      borderOpacity: 25,
      glowEnabled: true,
      glowColor: '#f5c518',
      glowIntensity: 'subtle',
    },
  },
  {
    id: 'jkkn-cream-glass',
    name: 'JKKN Cream Glass',
    category: 'brand',
    settings: {
      enabled: true,
      blurLevel: 'xl',
      backgroundOpacity: 15,
      variant: 'light',
      colorTint: 'jkkn-cream',
      tintOpacity: 20,
      borderEnabled: true,
      borderOpacity: 30,
      glowEnabled: false,
      glowIntensity: 'subtle',
    },
  },
]

// Generic Glass Presets
export const GENERIC_GLASS_PRESETS: GlassPreset[] = [
  {
    id: 'frosted-light',
    name: 'Frosted Light',
    category: 'generic',
    settings: {
      enabled: true,
      blurLevel: 'lg',
      backgroundOpacity: 10,
      variant: 'light',
      colorTint: 'none',
      tintOpacity: 15,
      borderEnabled: true,
      borderOpacity: 20,
      glowEnabled: false,
      glowIntensity: 'subtle',
    },
  },
  {
    id: 'frosted-dark',
    name: 'Frosted Dark',
    category: 'generic',
    settings: {
      enabled: true,
      blurLevel: 'lg',
      backgroundOpacity: 15,
      variant: 'dark',
      colorTint: 'none',
      tintOpacity: 15,
      borderEnabled: true,
      borderOpacity: 15,
      glowEnabled: false,
      glowIntensity: 'subtle',
    },
  },
  {
    id: 'blue-glass',
    name: 'Blue Glass',
    category: 'generic',
    settings: {
      enabled: true,
      blurLevel: 'lg',
      backgroundOpacity: 10,
      variant: 'light',
      colorTint: 'blue',
      tintOpacity: 15,
      borderEnabled: true,
      borderOpacity: 25,
      glowEnabled: false,
      glowIntensity: 'subtle',
    },
  },
  {
    id: 'purple-glass',
    name: 'Purple Glass',
    category: 'generic',
    settings: {
      enabled: true,
      blurLevel: 'lg',
      backgroundOpacity: 10,
      variant: 'light',
      colorTint: 'purple',
      tintOpacity: 15,
      borderEnabled: true,
      borderOpacity: 25,
      glowEnabled: false,
      glowIntensity: 'subtle',
    },
  },
  {
    id: 'cyan-glass',
    name: 'Cyan Glass',
    category: 'generic',
    settings: {
      enabled: true,
      blurLevel: 'lg',
      backgroundOpacity: 10,
      variant: 'light',
      colorTint: 'cyan',
      tintOpacity: 15,
      borderEnabled: true,
      borderOpacity: 25,
      glowEnabled: false,
      glowIntensity: 'subtle',
    },
  },
  {
    id: 'pink-glass',
    name: 'Pink Glass',
    category: 'generic',
    settings: {
      enabled: true,
      blurLevel: 'lg',
      backgroundOpacity: 10,
      variant: 'light',
      colorTint: 'pink',
      tintOpacity: 15,
      borderEnabled: true,
      borderOpacity: 25,
      glowEnabled: false,
      glowIntensity: 'subtle',
    },
  },
  {
    id: 'subtle-blur',
    name: 'Subtle Blur',
    category: 'generic',
    settings: {
      enabled: true,
      blurLevel: 'sm',
      backgroundOpacity: 5,
      variant: 'subtle',
      colorTint: 'none',
      tintOpacity: 10,
      borderEnabled: true,
      borderOpacity: 10,
      glowEnabled: false,
      glowIntensity: 'subtle',
    },
  },
  {
    id: 'strong-blur',
    name: 'Strong Blur',
    category: 'generic',
    settings: {
      enabled: true,
      blurLevel: '2xl',
      backgroundOpacity: 20,
      variant: 'strong',
      colorTint: 'none',
      tintOpacity: 20,
      borderEnabled: true,
      borderOpacity: 30,
      glowEnabled: false,
      glowIntensity: 'subtle',
    },
  },
]

// Combined presets
export const ALL_GLASS_PRESETS: GlassPreset[] = [
  ...JKKN_GLASS_PRESETS,
  ...GENERIC_GLASS_PRESETS,
]
